
CREATE TABLE room_location (
  id BIGINT NOT NULL DEFAULT NEXTVAL('global_seq'),
  type TEXT NOT NULL,
  group_name TEXT NOT NULL,
  name TEXT NOT NULL
);

INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Beastman of Farum Azula');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Bell Bearing Hunter');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Black Knife Assassin');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Bloodhound Knight Darriwil');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Crucible Knight');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Deathbird');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Demi-Human Chief');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Erdtree Burial Watchdog (Stormfoot Catacombs)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Flying Dragon Agheel');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Godrick the Grafted');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Grafted Scion');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Grave Warden Duelist');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Guardian Golem');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Mad Pumpkin Head');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Margit, the Fell Omen');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Night''s Cavalry');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Patches');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Soldier of Godrick');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Stonedigger Troll');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Tibia Mariner');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Tree Sentinel');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Limgrave', 'Ulcerated Tree Spirit');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Ancient Hero of Zamor');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Cemetery Shade');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Deathbird');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Erdtree Avatar');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Erdtree Burial Watchdog (Impaler''s Catacombs)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Leonine Misbegotten');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Miranda the Blighted Bloom');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Night''s Cavalry');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Runebear');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Weeping Peninsula', 'Scaly Misbegotten');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Adan, Thief of Fire');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Alabaster Lord');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Alecto, Black Knife Ringleader');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Bell Bearing Hunter');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Black Knife Assassin');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Bloodhound Knight');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Bols, Carian Knight');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Cemetery Shade');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Cleanrot Knight');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Crystalian');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Crystalian Spear & Crystalian Staff (Duo)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Death Rite Bird');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Deathbird');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Erdtree Avatar (Liurnia Northeast)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Erdtree Avatar (Liurnia Southwest)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Erdtree Burial Watchdog');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Glintstone Dragon Adula');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Glintstone Dragon Smarag');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Godskin Noble');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Magma Wyrm Makar');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Night''s Cavalry (Liurnia North)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Night''s Cavalry (Liurnia South)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Omenkiller');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Red Wolf of Radagon');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Rennala, Queen of the Full Moon');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Royal Knight Loretta');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Royal Revenant');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Spirit-Caller Snail');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Liurnia of the Lakes', 'Tibia Mariner');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Cemetery Shade');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Commander O''Neil');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Crucible Knight & Misbegotten Warrior');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Death Rite Bird');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Decaying Ekzykes');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Erdtree Avatar');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Erdtree Burial Watchdog (Duo)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Fallingstar Beast');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Frenzied Duelist');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Mad Pumpkin Heads');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Magma Wyrm');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Night''s Cavalry (Caelid)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Nox Swordstress & Nox Priest');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Caelid', 'Starscourge Radahn');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Battlemage Hugues');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Beastman of Farum Azula (Duo)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Bell Bearing Hunter');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Black Blade Kindred ');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Cleanrot Knight (Duo)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Elder Dragon Greyoll');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Flying Dragon Greyll');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Godskin Apostle');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Night''s Cavalry (Dragonbarrow)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Putrid Avatar');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Putrid Crystalian Trio');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Dragonbarrow', 'Putrid Tree Spirit');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Ancient Dragon Lansseax');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Ancient Hero of Zamor');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Black Knife Assassin (Sage''s Cave)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Black Knife Assassin (Sainted Hero''s Grave)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Crystalian Spear & Crystalian Ringblade');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Demi-Human Queen Gilika');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Elemer of the Briar');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Erdtree Burial Watchdog');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Fallingstar Beast');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Godefroy The Grafted');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Godskin Apostle');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Necromancer Garris');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Night''s Cavalry');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Omenkiller & Miranda the Blighted Bloom');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Perfumer Tricia & Misbegotten Warrior');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Sanguine Noble');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Stonedigger Troll');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Tibia Mariner');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Tree Sentinel (Duo)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Altus Plateau', 'Wormface');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'Abductor Virgins (Duo)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'Demi-Human Queen Maggie');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'Demi-Human Queen Margot');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'Full-Grown Fallingstar Beast');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'God-Devouring Serpent / Rykard, Lord of Blasphemy');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'Godskin Noble');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'Kindred of Rot (Duo)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'Magma Wyrm');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'Red Wolf of the Champion');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mt. Gelmir', 'Ulcerated Tree Spirit');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Capital Outskirts', 'Bell Bearing Hunter');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Capital Outskirts', 'Crucible Knight & Crucible Knight Ordovis');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Capital Outskirts', 'Deathbird');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Capital Outskirts', 'Draconic Tree Sentinel');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Capital Outskirts', 'Grave Warden Duelist');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Capital Outskirts', 'Onyx Lord');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Leyndell, Royal Capital', 'Esgar, Priest of Blood');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Leyndell, Royal Capital', 'Fell Twins');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Leyndell, Royal Capital', 'Godfrey, First Elden Lord');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Leyndell, Royal Capital', 'Mohg, the Omen');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Leyndell, Royal Capital', 'Morgott, the Omen King');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Ancient Hero of Zamor');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Borealis the Freezing Fog');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Commander Niall');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Death Rite Bird');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Erdtree Avatar');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Fire Giant');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Godskin Apostle and Godskin Noble (Spiritcaller Snail)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Tibia Mariner');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Ulcerated Tree Spirit');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Mountaintops of the Giants', 'Vyke, Knight of the Roundtable');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Crumbling Farum Azula', 'Beast Clergyman / Maliketh, the Black Blade');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Crumbling Farum Azula', 'Dragonlord Placidusax');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Crumbling Farum Azula', 'Godskin Duo');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Forbidden Lands', 'Black Blade Kindred');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Forbidden Lands', 'Night''s Cavalry');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Forbidden Lands', 'Stray Mimic Tear');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Consecrated Snowfield', 'Astel, Stars of Darkness');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Consecrated Snowfield', 'Death Rite Bird');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Consecrated Snowfield', 'Great Wyrm Theodorix');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Consecrated Snowfield', 'Misbegotten Crusader');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Consecrated Snowfield', 'Night''s Cavalry (Duo)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Consecrated Snowfield', 'Putrid Avatar');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Consecrated Snowfield', 'Putrid Grave Warden Duelist');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Miquella''s Haligtree', 'Loretta, Knight of the Haligtree');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Miquella''s Haligtree', 'Malenia, Blade of Miquella');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Siofra River', 'Ancestor Spirit');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Siofra River', 'Dragonkin Soldier');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Siofra River', 'Mohg, Lord of Blood');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Ainsel River', 'Dragonkin Soldier of Nokstella');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Nokron, Eternal City', 'Mimic Tear');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Nokron, Eternal City', 'Regal Ancestor Spirit');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Nokron, Eternal City', 'Valiant Gargoyle & Valiant Gargoyle (Twinblade)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Deeproot Depths', 'Crucible Knight Siluria');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Deeproot Depths', 'Fia''s Champions');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Deeproot Depths', 'Lichdragon Fortissax');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Lake of Rot', 'Astel, Naturalborn of the Void');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Lake of Rot', 'Dragonkin Soldier');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Leyndell, Ashen Capital', 'Esgar, Priest of Blood');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Leyndell, Ashen Capital', 'Godfrey, First Elden Lord (Hoarah Loux)');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Leyndell, Ashen Capital', 'Mohg, the Omen');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Leyndell, Ashen Capital', 'Sir Gideon Ofnir, the All-Knowing');
INSERT INTO room_location (type, group_name, name) VALUES ('BOSS', 'Elden Throne', 'Radagon of the Golden Order / Elden Beast');
